### ISSUE TITLE
Wybór biblioteki

### ISSUE THREAD

**Issue by maddie93** [maddie93/pt-net#1]
Ważne: licencja - darmowe, pozwalające na wykorzystanie, najlepiej open source

Propozycje:
http://www.jointjs.com/demos
http://js.cytoscape.org/ 
https://jsplumbtoolkit.com/demo/flowchart/dom.html
http://visjs.org/#gallery
http://d3js.org/ (przykład: http://bl.ocks.org/rkirsling/5001347)

Dodawajcie swoje albo wybierajcie z powyższych.

**Comment by wylly** [comment]
co do joint js: http://jointjs.com/demos/pn

**Comment by maddie93** [comment]
ode mnie jeszcze http://sigmajs.org/

**Comment by rprzystasz** [comment]
jointjs z tego co napisał @wylly ma obsługę dla sieci petriego więc było by to chyba easy mode 

trochę biedny framework bo w necie najpopularniejsze są te co wymieniłaś, ale wrzucę:
http://www.graphdracula.net/showcase/

tutaj jeszcze lista w razie czego:
http://jqueryhouse.com/javascript-chart-and-graph-libraries/

**Comment by maddie93** [comment]
Decyzja:
http://jointjs.com
http://jointjs.com/demos/pn

Bardzo proszę wszystkich o zapoznanie się z tematem, każdy potem coś zakodzi :)
